# Generated by Django 4.2.9 on 2024-02-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('followers', models.IntegerField()),
                ('avatar', models.URLField()),
                ('profile_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('main_text', models.TextField()),
                ('origin_url', models.URLField()),
                ('media', models.JSONField(blank=True, null=True)),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='hack_aggregator.author')),
            ],
        ),
    ]
