# Generated by Django 4.2.9 on 2024-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
